"""Create users table

Revision ID: 4d842e9e0f3b
Revises: 0b88cf63cd67
Create Date: 2024-11-21 11:54:08.242970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d842e9e0f3b'
down_revision: Union[str, None] = '0b88cf63cd67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('loginid', sa.String(length=16), nullable=False),
    sa.Column('mobile', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=48), nullable=True),
    sa.Column('google_id', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('last_passwd_change', sa.DateTime(), nullable=True),
    sa.Column('otp', sa.String(length=255), nullable=True),
    sa.Column('otp_gen_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=255), nullable=True),
    sa.Column('lang_pref', sa.String(length=16), nullable=True),
    sa.Column('tzone', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=24), nullable=True),
    sa.Column('office', sa.String(length=16), nullable=True),
    sa.Column('job_title', sa.String(length=24), nullable=True),
    sa.Column('mobile_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_otp', sa.String(length=255), nullable=True),
    sa.Column('email_otp_gen_at', sa.DateTime(), nullable=True),
    sa.Column('jwtoken', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['office'], ['offices.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role'], ['roles.role'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loginid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
