"""Create offices table

Revision ID: 90155b339e23
Revises: 
Create Date: 2024-11-21 11:38:06.735310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90155b339e23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('o_type', sa.String(length=24), nullable=False),
    sa.Column('ph_num1', sa.String(length=16), nullable=True),
    sa.Column('ph_num2', sa.String(length=16), nullable=True),
    sa.Column('email1', sa.String(length=48), nullable=True),
    sa.Column('email2', sa.String(length=48), nullable=True),
    sa.Column('website', sa.String(length=48), nullable=True),
    sa.Column('gst_num', sa.String(length=24), nullable=True),
    sa.Column('pincode', sa.String(length=8), nullable=True),
    sa.Column('country', sa.String(length=48), nullable=True),
    sa.Column('state', sa.String(length=48), nullable=True),
    sa.Column('district', sa.String(length=48), nullable=True),
    sa.Column('taluka', sa.String(length=48), nullable=True),
    sa.Column('place', sa.String(length=48), nullable=True),
    sa.Column('address_line1', sa.String(length=64), nullable=True),
    sa.Column('address_line2', sa.String(length=64), nullable=True),
    sa.Column('address_line3', sa.String(length=64), nullable=True),
    sa.Column('o_lat', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('o_long', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('notes', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_offices_active', 'offices', ['active'], unique=False)
    op.create_index('ix_offices_o_type', 'offices', ['o_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_offices_o_type', table_name='offices')
    op.drop_index('ix_offices_active', table_name='offices')
    op.drop_table('offices')
    # ### end Alembic commands ###
