"""Create privileges table

Revision ID: cb664f2bb93c
Revises: 90155b339e23
Create Date: 2024-11-21 11:39:33.114119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb664f2bb93c'
down_revision: Union[str, None] = '90155b339e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privileges',
    sa.Column('privilege', sa.String(length=24), nullable=False),
    sa.Column('tag', sa.String(length=24), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('privilege')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('privileges')
    # ### end Alembic commands ###
